# build from the Ubuntu 20.04 image
FROM ubuntu:20.04

# create the mssql user
RUN useradd -u 10001 mssql

# installing SQL Server
RUN apt-get update && apt-get install -y wget software-properties-common apt-transport-https
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2022.list)"
RUN apt-get update && apt-get install -y mssql-server

# creating directories to keep user databases seperate for system databases
RUN mkdir /var/opt/sqlserver
RUN mkdir /var/opt/sqlserver/data
RUN mkdir /var/opt/sqlserver/log
RUN mkdir /var/opt/sqlserver/backup

# set permissions on directories
RUN chown -R mssql /var/opt/sqlserver
RUN chown -R mssql /var/opt/mssql

# expose ports
EXPOSE 14331
EXPOSE 14332

# switching to the mssql user
USER mssql

# entry point
CMD [ "/opt/mssql/bin/sqlservr" ]
